# Generated by Django 2.2.3 on 2020-05-12 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20191021_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2020, 6, 1), verbose_name='Valid Until'),
        ),
    ]
